# Generated by Django 4.0.4 on 2022-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('questionLabel', models.CharField(max_length=100)),
                ('questionDataType', models.CharField(max_length=100)),
            ],
        ),
    ]
